/**
 * AUTO-GENERATED by scripts/extract-item-catalog.mjs — do not edit by hand.
 * Source: heroic-ai-rpg item blueprints (weaponLootTemplates, armorLootTemplates, itemRegistry, itemArtFamilies, materials).
 * Weapons/Protection subtypes are genre-scoped; fold via ITEM_ART_FAMILIES_BY_GENRE.
 * Sync: npm run sync:item-catalog
 *
 * Last synced: 2026-08-04
 */

export type ItemPortraitGenre = 'Fantasy' | 'Modern' | 'Sci-Fi';

export type ItemPortraitCategory =
  | 'Weapons'
  | 'Protection'
  | 'Accessories'
  | 'Wondrous'
  | 'Utilities'
  | 'Throwables'
  | 'Consumables'
  | 'Quest'
  | 'Material'
  | 'Currency';

export interface ItemPortraitCategoryEntry {
  readonly name: ItemPortraitCategory;
  readonly subtypes: readonly string[];
}

export const ITEM_PORTRAIT_CATALOG_BY_GENRE: Record<
  ItemPortraitGenre,
  readonly ItemPortraitCategoryEntry[]
> = {
  'Fantasy': [
    {
      name: 'Weapons',
      subtypes: [
      'Battleaxe',
      'Blowgun',
      'Bolas',
      'Chakram',
      'Club',
      'Crossbow',
      'Dagger',
      'Dart',
      'Disc Launcher',
      'Flail',
      'Glaive',
      'Greataxe',
      'Greatbow',
      'Greatclub',
      'Greatsword',
      'Halberd',
      'Hand Crossbow',
      'Handaxe',
      'Heavy Crossbow',
      'Heavy Throwing Harpoon',
      'Javelin',
      'Lance',
      'Light Hammer',
      'Longbow',
      'Longsword',
      'Mace',
      'Maul',
      'Morningstar',
      'Pike',
      'Punch Dagger',
      'Rapier',
      'Repeating Crossbow',
      'Scimitar',
      'Scythe',
      'Shortbow',
      'Shortsword',
      'Sickle',
      'Siege Cannon',
      'Sling',
      'Spear',
      'Spiked Gauntlet',
      'Throwing Star',
      'Trident',
      'War Pick',
      'Warhammer',
      'Whip',
    ],
    },
    {
      name: 'Protection',
      subtypes: [
      'Basic Shield',
      'Breastplate',
      'Chain Mail',
      'Chain Shirt',
      'Half Plate',
      'Heavy Shield',
      'Hide Armor',
      'Leather Armor',
      'Padded Armor',
      'Plate Armor',
      'Scale Mail',
      'Splint Armor',
      'Studded Leather',
    ],
    },
    {
      name: 'Accessories',
      subtypes: [
      'Amulet',
      'Ring',
      'Trinket',
    ],
    },
    {
      name: 'Wondrous',
      subtypes: [
      'Amulet Wear',
      'Belt',
      'Boots',
      'Bracers',
      'Circlet',
      'Cloak',
      'Gloves',
      'Goggles',
      'Greaves',
      'Robes',
      'Tunic',
      'Vestment',
    ],
    },
    {
      name: 'Utilities',
      subtypes: [
      'Energy Projector',
      'Grappling Hook',
      'Healer\'s Kit',
      'Heavy Ordnance',
      'Occult Mask',
      'Silk Rope (50ft)',
      'Spyglass',
      'Tech Gauntlet',
      'Thieves\' Tools',
      'Wand',
    ],
    },
    {
      name: 'Throwables',
      subtypes: [
      'Acid Vial',
      'Alchemist\'s Fire',
      'Explosive Charge',
      'Flash Powder',
      'Gas Canister',
      'Holy Water',
      'Incendiary Flask',
      'Smoke Grenade',
    ],
    },
    {
      name: 'Consumables',
      subtypes: [
      'Elixir of Focus',
      'Healing Potion',
      'Minor Healing Potion',
      'Potion of Agility',
      'Potion of Endurance',
      'Potion of Strength',
      'Scroll of Healing',
      'Scroll of Protection',
      'Scroll of Striking',
      'Vial of Resistance',
    ],
    },
    {
      name: 'Quest',
      subtypes: [
      'Ancient Relic',
      'Broken Emblem',
      'Heavy Iron Key',
      'Mysterious Note',
      'Signed Contract',
    ],
    },
    {
      name: 'Material',
      subtypes: [
      'Alloy',
      'Bio',
      'Bone',
      'Chemical',
      'Cloth',
      'Construction',
      'Data',
      'Dust',
      'Electronics',
      'Essence',
      'Exotic',
      'Flora',
      'Fluid',
      'Fuel',
      'Gas',
      'Gem',
      'Glass',
      'Hardware',
      'Leather',
      'Metal',
      'Optic',
      'Part',
      'Polymer',
      'Textile',
      'Wood',
    ],
    },
    {
      name: 'Currency',
      subtypes: [
      'Currency',
    ],
    }
  ],
  'Modern': [
    {
      name: 'Weapons',
      subtypes: [
      'Anti-Materiel Rifle',
      'Assault Rifle',
      'Autocannon',
      'Baseball Bat',
      'Bayonet',
      'Boarding Pike',
      'Brass Knuckles',
      'Breaching Hammer',
      'Carbine Rifle',
      'Chain Whip',
      'Chainsaw',
      'Combat Knife',
      'Compact Pistol',
      'Concrete Saw',
      'Crossbow Carbine',
      'Crowbar',
      'Entrenching Tool',
      'Expandable Baton',
      'Fire Axe',
      'Flamethrower',
      'Flashbang Launcher',
      'Garrote Wire',
      'Glass Shiv',
      'Grenade Launcher',
      'Industrial Cutter',
      'Karambit',
      'Katana',
      'Light Machine Gun',
      'Machete',
      'Mini Crossbow',
      'Minigun',
      'Mortar Tube',
      'Pepper Spray Gun',
      'Pipe Wrench',
      'Polearm Hook',
      'Pump Shotgun',
      'Riot Baton',
      'Riot Shield Maul',
      'Rocket Launcher',
      'Sap Gloves',
      'Service Pistol',
      'Signal Flare Gun',
      'Sledgehammer',
      'Sniper Rifle',
      'Stun Baton',
      'Submachine Gun',
      'Switchblade',
      'Tactical Spear',
      'Tactical Tomahawk',
      'Taser Pistol',
      'Wrecking Bar',
    ],
    },
    {
      name: 'Protection',
      subtypes: [
      'Ballistic Shield',
      'Ballistic Vest',
      'Bomb Suit',
      'Heavy Ballistic Armor',
      'Kevlar Vest',
      'Motorcycle Armor',
      'Plate Carrier',
      'Riot Shield',
      'Riot Suit',
      'Tactical Jacket',
    ],
    },
    {
      name: 'Accessories',
      subtypes: [
      'Amulet',
      'Ring',
      'Trinket',
    ],
    },
    {
      name: 'Wondrous',
      subtypes: [
      'Amulet Wear',
      'Belt',
      'Boots',
      'Bracers',
      'Circlet',
      'Cloak',
      'Gloves',
      'Goggles',
      'Greaves',
      'Robes',
      'Tunic',
      'Vestment',
    ],
    },
    {
      name: 'Utilities',
      subtypes: [
      'Energy Projector',
      'Grappling Hook',
      'Healer\'s Kit',
      'Heavy Ordnance',
      'Occult Mask',
      'Silk Rope (50ft)',
      'Spyglass',
      'Tech Gauntlet',
      'Thieves\' Tools',
      'Wand',
    ],
    },
    {
      name: 'Throwables',
      subtypes: [
      'Acid Vial',
      'Alchemist\'s Fire',
      'Explosive Charge',
      'Flash Powder',
      'Gas Canister',
      'Holy Water',
      'Incendiary Flask',
      'Smoke Grenade',
    ],
    },
    {
      name: 'Consumables',
      subtypes: [
      'Elixir of Focus',
      'Healing Potion',
      'Minor Healing Potion',
      'Potion of Agility',
      'Potion of Endurance',
      'Potion of Strength',
      'Scroll of Healing',
      'Scroll of Protection',
      'Scroll of Striking',
      'Vial of Resistance',
    ],
    },
    {
      name: 'Quest',
      subtypes: [
      'Ancient Relic',
      'Broken Emblem',
      'Heavy Iron Key',
      'Mysterious Note',
      'Signed Contract',
    ],
    },
    {
      name: 'Material',
      subtypes: [
      'Alloy',
      'Bio',
      'Bone',
      'Chemical',
      'Cloth',
      'Construction',
      'Data',
      'Dust',
      'Electronics',
      'Essence',
      'Exotic',
      'Flora',
      'Fluid',
      'Fuel',
      'Gas',
      'Gem',
      'Glass',
      'Hardware',
      'Leather',
      'Metal',
      'Optic',
      'Part',
      'Polymer',
      'Textile',
      'Wood',
    ],
    },
    {
      name: 'Currency',
      subtypes: [
      'Currency',
    ],
    }
  ],
  'Sci-Fi': [
    {
      name: 'Weapons',
      subtypes: [
      'Acid Sprayer',
      'Arc Blaster',
      'Arc Rifle',
      'Chainblade',
      'Cryo Pistol',
      'Cryo Rifle',
      'Disruptor Blade',
      'Disruptor Rifle',
      'Fusion Beam',
      'Fusion Cutter',
      'Gauss Rifle',
      'Grav Hammer',
      'Grav Launcher',
      'Grav Maul',
      'Heavy Laser Cannon',
      'Industrial Vibro Axe',
      'Ion Accelerator',
      'Ion Carbine',
      'Ion Knuckles',
      'Ion Pistol',
      'Kinetic Greatclub',
      'Kinetic Mace',
      'Laser Pistol',
      'Laser Rifle',
      'Mono Knife',
      'Mono Pike',
      'Mono Spear',
      'Nanite Whip',
      'Needle Needler',
      'Needle Rifle',
      'Particle Beam',
      'Photon Beamer',
      'Photon Dartgun',
      'Plasma Cannon',
      'Plasma Edge',
      'Plasma Greatblade',
      'Power Halberd',
      'Power Maul',
      'Pulse Carbine',
      'Pulse Rifle',
      'Punch Spike',
      'Rail Carbine',
      'Railgun',
      'Shock Baton',
      'Shock Glaive',
      'Shock Lance',
      'Sonic Emitter',
      'Stun Prod',
      'Thermal Blade',
      'Thermal Cutter',
      'Thermal Scythe',
      'Vibro Axe',
      'Vibro Blade',
      'Vibro Hatchet',
      'Vibro Saber',
      'Void Cannon',
      'Void Cleaver',
    ],
    },
    {
      name: 'Protection',
      subtypes: [
      'Adaptive Carapace',
      'Combat Mesh',
      'Energy Buckler',
      'Hardlight Shield',
      'Mesh Underlay',
      'Power Armor',
      'Reflex Armor',
      'Siege Frame',
      'Stealth Skinsuit',
      'Voidshield Plate',
    ],
    },
    {
      name: 'Accessories',
      subtypes: [
      'Amulet',
      'Ring',
      'Trinket',
    ],
    },
    {
      name: 'Wondrous',
      subtypes: [
      'Amulet Wear',
      'Belt',
      'Boots',
      'Bracers',
      'Circlet',
      'Cloak',
      'Gloves',
      'Goggles',
      'Greaves',
      'Robes',
      'Tunic',
      'Vestment',
    ],
    },
    {
      name: 'Utilities',
      subtypes: [
      'Energy Projector',
      'Grappling Hook',
      'Healer\'s Kit',
      'Heavy Ordnance',
      'Occult Mask',
      'Silk Rope (50ft)',
      'Spyglass',
      'Tech Gauntlet',
      'Thieves\' Tools',
      'Wand',
    ],
    },
    {
      name: 'Throwables',
      subtypes: [
      'Acid Vial',
      'Alchemist\'s Fire',
      'Explosive Charge',
      'Flash Powder',
      'Gas Canister',
      'Holy Water',
      'Incendiary Flask',
      'Smoke Grenade',
    ],
    },
    {
      name: 'Consumables',
      subtypes: [
      'Elixir of Focus',
      'Healing Potion',
      'Minor Healing Potion',
      'Potion of Agility',
      'Potion of Endurance',
      'Potion of Strength',
      'Scroll of Healing',
      'Scroll of Protection',
      'Scroll of Striking',
      'Vial of Resistance',
    ],
    },
    {
      name: 'Quest',
      subtypes: [
      'Ancient Relic',
      'Broken Emblem',
      'Heavy Iron Key',
      'Mysterious Note',
      'Signed Contract',
    ],
    },
    {
      name: 'Material',
      subtypes: [
      'Alloy',
      'Bio',
      'Bone',
      'Chemical',
      'Cloth',
      'Construction',
      'Data',
      'Dust',
      'Electronics',
      'Essence',
      'Exotic',
      'Flora',
      'Fluid',
      'Fuel',
      'Gas',
      'Gem',
      'Glass',
      'Hardware',
      'Leather',
      'Metal',
      'Optic',
      'Part',
      'Polymer',
      'Textile',
      'Wood',
    ],
    },
    {
      name: 'Currency',
      subtypes: [
      'Currency',
    ],
    }
  ],
};

/** Fantasy catalog — backward-compatible flat export. */
export const ITEM_PORTRAIT_CATALOG: readonly ItemPortraitCategoryEntry[] =
  ITEM_PORTRAIT_CATALOG_BY_GENRE.Fantasy;

/** Member chassis → shared art family, per genre. */
export const ITEM_ART_FAMILIES_BY_GENRE: Readonly<
  Record<ItemPortraitGenre, Readonly<Record<string, string>>>
> = {
  'Fantasy': {
    'Arbalest': 'Heavy Crossbow',
    'Banded Mail': 'Splint Armor',
    'Bastard Sword': 'Longsword',
    'Bullet Sling': 'Sling',
    'Composite Bow': 'Longbow',
    'Cuirbouli Vest': 'Leather Armor',
    'Dragon-Bane Crossbow': 'Heavy Crossbow',
    'Heavy Sling': 'Sling',
    'Pocket Crossbow': 'Hand Crossbow',
    'Portable Ballista': 'Heavy Crossbow',
    'Quilted Gambeson': 'Padded Armor',
    'Recurve Bow': 'Longbow',
    'Ring Mail': 'Chain Mail',
    'Siege Bow': 'Greatbow',
    'Throwing Axe': 'Handaxe',
    'Throwing Dagger': 'Dagger',
    'Throwing Hammer': 'Warhammer',
    'Throwing Spear': 'Javelin',
  },
  'Modern': {
    'Automatic Shotgun': 'Pump Shotgun',
    'Battle Rifle': 'Carbine Rifle',
    'Ceramic Insert Vest': 'Plate Carrier',
    'Designated Marksman Rifle': 'Carbine Rifle',
    'EOD Suit': 'Bomb Suit',
    'Heavy Shotgun': 'Pump Shotgun',
    'Hunting Rifle': 'Carbine Rifle',
    'Machine Pistol': 'Compact Pistol',
    'Pocket Shotgun': 'Pump Shotgun',
    'Snubnose Revolver': 'Compact Pistol',
    'Soft Body Armor': 'Kevlar Vest',
    'Stab Vest': 'Kevlar Vest',
    'SWAT Armor': 'Heavy Ballistic Armor',
    'Tactical Armor': 'Ballistic Vest',
    'Throwing Knife': 'Combat Knife',
  },
  'Sci-Fi': {
    'Battleplate Harness': 'Power Armor',
    'Cryo Projector': 'Cryo Rifle',
    'Force Barrier Disk': 'Hardlight Shield',
    'Hardlight Vest': 'Combat Mesh',
    'Heavy Exosuit': 'Power Armor',
    'Light Flexsuit': 'Mesh Underlay',
    'Medium Exosuit Plating': 'Adaptive Carapace',
    'Plasma Pistol': 'Laser Pistol',
    'Plasma Rifle': 'Laser Rifle',
    'Soft Shell Armor': 'Mesh Underlay',
    'Synthweave Suit': 'Mesh Underlay',
  },
};

/** Fantasy art families — backward-compatible flat export. */
export const ITEM_ART_FAMILIES: Readonly<Record<string, string>> =
  ITEM_ART_FAMILIES_BY_GENRE.Fantasy;

const normalizeArtFamilyKey = (value: string | null | undefined): string =>
  (value || '').trim().toLowerCase();

export function resolveItemPortraitGenre(
  genre: string | null | undefined
): ItemPortraitGenre {
  const key = (genre || 'Fantasy').toString().toLowerCase();
  if (key.includes('sci')) return 'Sci-Fi';
  if (key.includes('modern')) return 'Modern';
  return 'Fantasy';
}

/** Fold a chassis or family name to the upload / match art-family key. */
export function resolveItemArtFamily(
  name: string,
  genre: string | null | undefined = 'Fantasy'
): string {
  const trimmed = (name || '').trim();
  if (!trimmed) return trimmed;
  const map = ITEM_ART_FAMILIES_BY_GENRE[resolveItemPortraitGenre(genre)];
  const target = normalizeArtFamilyKey(trimmed);
  for (const [member, family] of Object.entries(map)) {
    if (normalizeArtFamilyKey(member) === target) return family;
  }
  return trimmed;
}

/** Family representative plus every chassis that shares its image bucket. */
export function getItemArtFamilyMembers(
  familyOrMember: string,
  genre: string | null | undefined = 'Fantasy'
): string[] {
  const resolvedGenre = resolveItemPortraitGenre(genre);
  const family = resolveItemArtFamily(familyOrMember, resolvedGenre);
  if (!family) return [];
  const map = ITEM_ART_FAMILIES_BY_GENRE[resolvedGenre];
  const familyKey = normalizeArtFamilyKey(family);
  const members = new Set<string>([family]);
  for (const [member, mapped] of Object.entries(map)) {
    if (normalizeArtFamilyKey(mapped) === familyKey) {
      members.add(member);
      members.add(mapped);
    }
  }
  return [...members];
}

export const getItemPortraitCategoryNames = (
  genre: string | null | undefined = 'Fantasy'
): readonly ItemPortraitCategory[] =>
  ITEM_PORTRAIT_CATALOG_BY_GENRE[resolveItemPortraitGenre(genre)].map((entry) => entry.name);

/** Art-family names for Weapons/Protection; exact template names for other categories. */
export const getItemPortraitSubtypes = (
  category: string,
  genre: string | null | undefined = 'Fantasy'
): readonly string[] => {
  const resolvedGenre = resolveItemPortraitGenre(genre);
  const normalized = category.trim().toLowerCase();
  const entry = ITEM_PORTRAIT_CATALOG_BY_GENRE[resolvedGenre].find(
    (row) => row.name.toLowerCase() === normalized
  );
  return entry?.subtypes ?? [];
};
