/**
 * AUTO-GENERATED by scripts/extract-item-catalog.mjs — do not edit by hand.
 * Source: heroic-ai-rpg item blueprints (weaponLootTemplates, itemRegistry, itemArtFamilies, materials).
 * Weapons/Protection subtypes are art-family names (folded via ITEM_ART_FAMILIES).
 * Sync: npm run sync:item-catalog
 *
 * Last synced: 2026-08-04
 */

export type ItemPortraitCategory =
  | 'Weapons'
  | 'Protection'
  | 'Accessories'
  | 'Wondrous'
  | 'Utilities'
  | 'Throwables'
  | 'Consumables'
  | 'Quest'
  | 'Material'
  | 'Currency';

export interface ItemPortraitCategoryEntry {
  readonly name: ItemPortraitCategory;
  readonly subtypes: readonly string[];
}

export const ITEM_PORTRAIT_CATALOG: readonly ItemPortraitCategoryEntry[] = [
  {
    name: 'Weapons',
    subtypes: [
    'Battleaxe',
    'Blowgun',
    'Bolas',
    'Chakram',
    'Club',
    'Crossbow',
    'Dagger',
    'Dart',
    'Disc Launcher',
    'Flail',
    'Glaive',
    'Greataxe',
    'Greatbow',
    'Greatclub',
    'Greatsword',
    'Halberd',
    'Hand Crossbow',
    'Handaxe',
    'Heavy Crossbow',
    'Heavy Throwing Harpoon',
    'Javelin',
    'Lance',
    'Light Hammer',
    'Longbow',
    'Longsword',
    'Mace',
    'Maul',
    'Morningstar',
    'Pike',
    'Punch Dagger',
    'Rapier',
    'Repeating Crossbow',
    'Scimitar',
    'Scythe',
    'Shortbow',
    'Shortsword',
    'Sickle',
    'Siege Cannon',
    'Sling',
    'Spear',
    'Spiked Gauntlet',
    'Throwing Star',
    'Trident',
    'War Pick',
    'Warhammer',
    'Whip',
  ],
  },
  {
    name: 'Protection',
    subtypes: [
    'Basic Shield',
    'Breastplate',
    'Chain Mail',
    'Chain Shirt',
    'Half Plate',
    'Heavy Shield',
    'Hide Armor',
    'Leather Armor',
    'Padded Armor',
    'Plate Armor',
    'Scale Mail',
    'Splint Armor',
    'Studded Leather',
  ],
  },
  {
    name: 'Accessories',
    subtypes: [
    'Amulet',
    'Ring',
    'Trinket',
  ],
  },
  {
    name: 'Wondrous',
    subtypes: [
    'Amulet Wear',
    'Belt',
    'Boots',
    'Bracers',
    'Circlet',
    'Cloak',
    'Gloves',
    'Goggles',
    'Greaves',
    'Robes',
    'Tunic',
    'Vestment',
  ],
  },
  {
    name: 'Utilities',
    subtypes: [
    'Energy Projector',
    'Grappling Hook',
    'Healer\'s Kit',
    'Heavy Ordnance',
    'Occult Mask',
    'Silk Rope (50ft)',
    'Spyglass',
    'Tech Gauntlet',
    'Thieves\' Tools',
    'Wand',
  ],
  },
  {
    name: 'Throwables',
    subtypes: [
    'Acid Vial',
    'Alchemist\'s Fire',
    'Explosive Charge',
    'Flash Powder',
    'Gas Canister',
    'Holy Water',
    'Incendiary Flask',
    'Smoke Grenade',
  ],
  },
  {
    name: 'Consumables',
    subtypes: [
    'Elixir of Focus',
    'Healing Potion',
    'Minor Healing Potion',
    'Potion of Agility',
    'Potion of Endurance',
    'Potion of Strength',
    'Scroll of Healing',
    'Scroll of Protection',
    'Scroll of Striking',
    'Vial of Resistance',
  ],
  },
  {
    name: 'Quest',
    subtypes: [
    'Ancient Relic',
    'Broken Emblem',
    'Heavy Iron Key',
    'Mysterious Note',
    'Signed Contract',
  ],
  },
  {
    name: 'Material',
    subtypes: [
    'Alloy',
    'Bio',
    'Bone',
    'Chemical',
    'Cloth',
    'Construction',
    'Data',
    'Dust',
    'Electronics',
    'Essence',
    'Exotic',
    'Flora',
    'Fluid',
    'Fuel',
    'Gas',
    'Gem',
    'Glass',
    'Hardware',
    'Leather',
    'Metal',
    'Optic',
    'Part',
    'Polymer',
    'Textile',
    'Wood',
  ],
  },
  {
    name: 'Currency',
    subtypes: [
    'Currency',
  ],
  }
];

export const getItemPortraitCategoryNames = (): readonly ItemPortraitCategory[] =>
  ITEM_PORTRAIT_CATALOG.map((entry) => entry.name);

export const getItemPortraitSubtypes = (category: string): readonly string[] => {
  const normalized = category.trim().toLowerCase();
  const entry = ITEM_PORTRAIT_CATALOG.find((row) => row.name.toLowerCase() === normalized);
  return entry?.subtypes ?? [];
};
