/**
 * AUTO-GENERATED by scripts/extract-origin-item-catalog.mjs — do not edit by hand.
 *
 * Origin Item catalog for Media Library uploads.
 * Source of truth: heroic-ai-rpg/src/config/startingStories.ts
 *
 * Regenerate:
 *   npm run sync:origin-item-catalog
 *
 * Last synced: 2026-08-31
 *
 * One picture per origin keepsake. The live game looks up keepsake art with:
 *   GET /api/image-assets/origin-item-defaults?startingStoryId=<id>
 * expecting assetType "Origin Item", genre "Any Genre", and
 * metadata.startingStoryId equal to one of these ids.
 */

export interface OriginItemOption {
  id: string;
  name: string;
  storyTitle: string;
  description: string;
  itemType: string;
}

export const ORIGIN_ITEM_OPTIONS: readonly OriginItemOption[] = [
  {
    id: 'humble_beginnings',
    name: "Woven Kinship Locket",
    storyTitle: "Humble Beginnings",
    description: "A hand-carved wooden locket containing a braid of kin-spun fiber, reminding you of the home you defend.",
    itemType: "Amulet",
  },
  {
    id: 'the_drifter',
    name: "Wayfarer's Carved Flint",
    storyTitle: "The Drifter",
    description: "A well-worn survival tool etched with compass marks, essential for sparking trail fires in freezing wilderness.",
    itemType: "Survival Kit",
  },
  {
    id: 'the_blank_slate',
    name: "Etched Cipher Token",
    storyTitle: "The Blank Slate",
    description: "A heavy metallic token inscribed with shifting, unreadable glyphs found on your person upon awakening.",
    itemType: "Trinket",
  },
  {
    id: 'the_pariah',
    name: "Tarnished Brand Shackle",
    storyTitle: "The Pariah",
    description: "A filed-down iron cuff from your exile tribunal, kept as a silent testament of defiance and survival.",
    itemType: "Trophy",
  },
  {
    id: 'the_fallen_house',
    name: "Tarnished Signet Ring",
    storyTitle: "The Fallen House",
    description: "A heavy signet ring bearing your house crest, scratched and obscured to hide your identity from usurpers.",
    itemType: "Ring",
  }
] as const;

export type OriginItemStartingStoryId = (typeof ORIGIN_ITEM_OPTIONS)[number]['id'];

const ORIGIN_ITEM_IDS = new Set<string>(ORIGIN_ITEM_OPTIONS.map((option) => option.id));

export const isOriginItemStartingStoryId = (value: string): value is OriginItemStartingStoryId =>
  ORIGIN_ITEM_IDS.has(value);

export const getOriginItemOption = (startingStoryId: string): OriginItemOption | undefined =>
  ORIGIN_ITEM_OPTIONS.find((option) => option.id === startingStoryId);

export const getOriginItemDisplayName = (startingStoryId: string): string =>
  ORIGIN_ITEM_OPTIONS.find((option) => option.id === startingStoryId)?.name || startingStoryId;

export const getOriginItemStoryTitle = (startingStoryId: string): string =>
  ORIGIN_ITEM_OPTIONS.find((option) => option.id === startingStoryId)?.storyTitle || startingStoryId;

export const getOriginItemDescription = (startingStoryId: string): string =>
  ORIGIN_ITEM_OPTIONS.find((option) => option.id === startingStoryId)?.description || '';

export const getOriginItemType = (startingStoryId: string): string =>
  ORIGIN_ITEM_OPTIONS.find((option) => option.id === startingStoryId)?.itemType || '';
