/**
 * AUTO-GENERATED by scripts/extract-rideable-catalog.mjs — do not edit by hand.
 * Source: heroic-ai-rpg/src/constants/rideableCatalog.ts
 * Sync: npm run sync:rideable-catalog
 */

export type RideablePortraitGenre = 'Fantasy' | 'Modern' | 'Sci-Fi';
export type RideablePortraitCategory = 'mount' | 'vehicle' | 'ship';

export const RIDEABLE_PORTRAIT_CATALOG: Record<
  RideablePortraitGenre,
  Record<RideablePortraitCategory, readonly string[]>
> = {
  Fantasy: {
    mount: [
    'War Destrier',
    'Elven Stag',
    'Dire Wolf',
    'Giant Eagle',
    'Pack Mule',
    'Griffon',
    'Cave Bear',
    'Shadow Panther',
  ],
    vehicle: [],
    ship: [
    'Wind Skiff',
    'Cloud Sloop',
    'Moonwing Cutter',
    'Sky Galleon',
    'Solar Schooner',
    'Phantom Skiff',
    'Star Cathedral',
    'Astral Galleon',
  ],
  },
  Modern: {
    mount: [
    'Hunting Dog',
    'K9 Unit',
    'Trained Hawk',
    'Trained Eagle',
    'Brown Bear',
    'Riding Horse',
    'Police Horse',
    'Mountain Lion',
  ],
    vehicle: [
    'Cargo Truck',
    'Sedan Coupe',
    'Delivery Van',
    'Offroad Camper',
    'Utility Pickup',
    'City Scooter',
    'Airport Shuttle',
    'Flatbed Hauler',
    'Street Motorcycle',
    'Touring Motorcycle',
    'Dirt Bike',
    'Trail Quad',
  ],
    ship: [
    'Medevac VTOL',
    'Stealth VTOL',
    'Tiltrotor Gunship',
    'Skyfort Carrier',
    'Rescue Lander',
    'Uplink Lander',
    'Haven Lander',
    'Starlifter Hauler',
  ],
  },
  'Sci-Fi': {
    mount: [
    'Hover-Bike',
    'Mech-Walker',
    'Recon Glider',
    'Xeno-Raptor',
    'Grav Steed',
    'Plasma Charger',
    'Void Hound',
    'Mag-Rail Strider',
  ],
    vehicle: [
    'Cargo Skiff',
    'Speeder Taxi',
    'Colony Rover',
    'Mining Crawler',
    'Orbital Shuttle Pod',
    'Grav Wagon',
    'Survey Buggy',
    'Utility Drone Cart',
  ],
    ship: [
    'Heavy Dreadnought',
    'Stealth Interceptor',
    'Science Explorer',
    'Medical Frigate',
    'Smuggler\'s Runner',
    'Freighter Hauler',
    'Fighter Wingcraft',
    'Colony Transport',
    'Merchant Yacht',
    'Strike Corvette',
    'Blockade Breaker',
  ],
  },
};

export const getRideableTypeSuggestions = (
  genre: RideablePortraitGenre,
  category: RideablePortraitCategory
): readonly string[] => RIDEABLE_PORTRAIT_CATALOG[genre]?.[category] ?? [];
