/**
 * AUTO-GENERATED by scripts/extract-rideable-catalog.mjs — do not edit by hand.
 * Source: heroic-ai-rpg/src/constants/rideableCatalog.ts
 * Sync: npm run sync:rideable-catalog
 */

export type RideablePortraitGenre = 'Fantasy' | 'Modern' | 'Sci-Fi';
export type RideablePortraitCategory = 'mount' | 'vehicle' | 'ship';

export const RIDEABLE_PORTRAIT_CATALOG: Record<
  RideablePortraitGenre,
  Record<RideablePortraitCategory, readonly string[]>
> = {
  Fantasy: {
    mount: [
    'War Destrier',
    'Elven Stag',
    'Dire Wolf',
    'Giant Eagle',
    'Pack Mule',
    'Griffon',
    'Cave Bear',
    'Shadow Panther',
  ],
    vehicle: [
    'Travel Wagon',
    'Merchant Cart',
    'War Chariot',
    'Royal Carriage',
    'Mining Sled',
    'Supply Caravan',
    'Balloon Gondola',
    'Covered Coach',
  ],
    ship: [
    'War Galley',
    'Elven Cutter',
    'Ghost Ship',
    'Floating Cathedral',
    'Explorer Cog',
    'Galleon',
    'Sloop',
    'Coastal Skiff',
  ],
  },
  Modern: {
    mount: [
    'Patrol Motorcycle',
    'Armored Suv',
    'Dirt Bike',
    'Tactical Quad',
    'Pursuit Interceptor',
    'Riot Apc',
    'Combat Atv',
    'Enforcer Cruiser',
  ],
    vehicle: [
    'Cargo Truck',
    'Sedan Coupe',
    'Delivery Van',
    'Offroad Camper',
    'Utility Pickup',
    'City Scooter',
    'Airport Shuttle',
    'Flatbed Hauler',
  ],
    ship: [
    'SWAT Command Van',
    'SNN Broadcast Truck',
    'Response Unit',
    'Hauler Juggernaut',
    'Mobile Safehouse',
    'Coast Guard Cutter',
    'News Helicopter',
    'Harbor Tugboat',
  ],
  },
  'Sci-Fi': {
    mount: [
    'Hover-Bike',
    'Mech-Walker',
    'Recon Glider',
    'Xeno-Raptor',
    'Grav Steed',
    'Plasma Charger',
    'Void Hound',
    'Mag-Rail Strider',
  ],
    vehicle: [
    'Cargo Skiff',
    'Speeder Taxi',
    'Colony Rover',
    'Mining Crawler',
    'Orbital Shuttle Pod',
    'Grav Wagon',
    'Survey Buggy',
    'Utility Drone Cart',
  ],
    ship: [
    'Heavy Dreadnought',
    'Stealth Interceptor',
    'Science Explorer',
    'Medical Frigate',
    'Smuggler\'s Runner',
    'Freighter Hauler',
    'Fighter Wingcraft',
    'Colony Transport',
  ],
  },
};

export const getRideableTypeSuggestions = (
  genre: RideablePortraitGenre,
  category: RideablePortraitCategory
): readonly string[] => RIDEABLE_PORTRAIT_CATALOG[genre]?.[category] ?? [];
